In [13]:
#import libraries
import pandas as pd
import plotly.express as px

In [40]:
#load dataframe with % completion information of projects and set title
#df = pd.read_csv('2023_11_03_3950_AB_compl.csv')
#titulo = 'Lambda A-B max'
#df = pd.read_csv('2023_11_03_3950_A_compl.csv')
#titulo = 'Lambda A max'
df = pd.read_csv('2023_11_03_3950_77_compl.csv')
titulo = 'Lambda max'

In [ ]:
#load dataframes of % completion information of SB_UIDs
#df = pd.read_csv('2023_11_14_3950_AB_compl.csv')
#titulo = 'Lambda A-B max SB'
#df = pd.read_csv('2023_11_14_3950_A_compl.csv')
#titulo = 'Lambda A max SB'
#df = pd.read_csv('2023_11_14_3950_77_compl.csv')
#titulo = 'Lambda max SB'

In [41]:
df.head()

       Unnamed: 0  compl grade
0  2022.1.00360.S    0.0     C
1  2022.1.00474.S  100.0     B
2  2022.1.00439.S    0.0     B
3  2022.1.00445.S  100.0     B
4  2022.1.00454.S  100.0     C

In [42]:
#create function to categorize projects in the categories
def completion(x):
    if x == 0:
        return 'Not Observed'
    elif x < 100:
        return 'Partially Observed'
    elif x == 100:
        return 'Completed'
    else:
        return pd.NaT

In [43]:
df['Completion'] = df.compl.apply(completion) #apply function

In [44]:
count_by_grade_comp = df.groupby(['grade', 'Completion']).count() #get amount of projects in categories and grade

In [45]:
count_by_grade = df.groupby(['grade']).count() #get amount of projects per grade

In [46]:
count_by_grade_comp = count_by_grade_comp.reset_index().set_index('grade') #set grade as index

In [47]:
count_by_grade_comp['Percentage'] = 0 #create Percentage column

In [48]:
#calculate percetages per grade
count_by_grade_comp.loc['A', 'Percentage'] = 100 * count_by_grade_comp.loc['A', 'compl'] / count_by_grade.loc['A', 'compl']
count_by_grade_comp.loc['B', 'Percentage'] = 100 * count_by_grade_comp.loc['B', 'compl'] / count_by_grade.loc['B', 'compl']
count_by_grade_comp.loc['C', 'Percentage'] = 100 * count_by_grade_comp.loc['C', 'compl'] / count_by_grade.loc['C', 'compl']

In [49]:
#create palette for plot
custom_palette = {'Completed': '#5799C7', 'Partially Observed': '#C3D5EE', 'Not Observed': '#FF9F4B'}

In [50]:
#create plot
px.bar(count_by_grade_comp.reset_index(), 
             x='grade', 
             y='Percentage', 
             color='Completion',
             category_orders={'grade': ['A', 'B', 'C'], 'completion': ['Completed', 'Partially Observed', 'Not Observed']},
             color_discrete_map=custom_palette,
             #title=titulo,
             text_auto='.2s')

In [51]:
count_by_grade_comp

               Completion  Unnamed: 0  compl  Percentage
grade
A               Completed          52     52   86.666667
A            Not Observed           6      6   10.000000
A      Partially Observed           2      2    3.333333
B               Completed         117    117   70.059880
B            Not Observed          49     49   29.341317
B      Partially Observed           1      1    0.598802
C               Completed         153    153   80.526316
C            Not Observed          37     37   19.473684